### ISSUE TITLE
Congrats made it to the front page of GitHub. But your read me says nothing constructive about the program. What is it for? Something Minecraft related I’d assume?

### ISSUE THREAD

**Issue by Dax911** [Hqrion-Clientz/Phobos-1.9.0-BUILDABLE-SRC#24]

**Comment by Hqrion** [comment]
Yes, Phobos is a minecraft hacked client aimed torwards anarchy servers for 1.12.2. Phobos has been known to have contained malware due to clashes with other client(s), and people like me and others have decided to decompile, and remap their client and ensure it's safe for others to use to prevent others from getting infected from potential malware.

**Comment by Dax911** [comment]
Oh thats badass. I work with the minecraft at home team doing seed finding. I would love to jump into learning more let me know if I can contribute!

**Comment by Hqrion** [comment]
Sure, would be cool to talk with you. If you have discord, please add me on Hqrion#9210, if you don't have discord that's fine! Feel free to contribute to any future projects I may upload.
